# Exercises XP: Vector Databases and RAG
Use this guided notebook and fill each TODO before running cells.

## What you'll learn
- Vector search strategies (KNN, ANN) and evaluation.
- Vector database utility (similarity search, RAG).
- Differences between vector DBs, libraries, and plugins.
- Best practices for vector store usage and performance.
- How LMs use context; embedding generation and storage.
- Querying vector stores and applying LMs for QA with retrieved context.

## What you'll build
A functional RAG pipeline with FAISS and ChromaDB, plus QA over retrieved context using a Hugging Face model.

## 0. Setup
Run the install cell once. If your platform needs system deps (e.g., libomp for FAISS), follow instructions in comments.

In [1]:
%pip uninstall -y pydantic-core pydantic
%pip install -U "pydantic<2"
%pip install -U "faiss-cpu>=1.8.0" "chromadb==0.3.21"
%pip install -U "numpy<2" sentence-transformers transformers

Found existing installation: pydantic_core 2.50.1
Uninstalling pydantic_core-2.50.1:
  Successfully uninstalled pydantic_core-2.50.1
Found existing installation: pydantic 2.14.1
Uninstalling pydantic-2.14.1:
  Successfully uninstalled pydantic-2.14.1
Note: you may need to restart the kernel to use updated packages.
Collecting pydantic<2
  Using cached pydantic-1.10.26-cp312-cp312-win_amd64.whl.metadata (156 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic<2) (4.16.0)
Using cached pydantic-1.10.26-cp312-cp312-win_amd64.whl (1.9 MB)
Installing collected packages: pydantic
Successfully installed pydantic-1.10.26
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chromadb 1.5.9 requires pydantic>=2.0, but you have pydantic 1.10.26 which is incompatible.
kubernetes 37.0.1 requires pydantic>=2.13.5, but you have pydantic 1.10.26 which is incompatible.
pydantic-settings 2.16.0 requires pydantic>=2.7.0, but you have pydantic 1.10.26 which is incompatible.
spacy 3.8.16 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.26 which is incompatible.
thinc 8.3.13 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.26 which is incompatible.
weasel 1.0.0 requires pydantic>=2.0.0, but you have pydantic 1.10.26 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: faiss-cpu>=1.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (1.15.1)
Collecting chromadb==0.3.21
  Using cached chromadb-0.3.21-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: pandas>=1.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb==0.3.21) (3.0.5)
Requirement already satisfied: requests>=2.28 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb==0.3.21) (2.34.2)
Requirement already satisfied: pydantic>=1.9 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb==0.3.21) (1.10.26)
Collecting hnswlib>=0.7 (from chromadb==0.3.21)
  Using cached hnswlib-0.8.0.tar.gz (36 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting clickhouse-connect>=0.5.7 (from chromadb==0.3.21)
  Using cached clickhouse_connect-1.11.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: sentence-transformers>=2.2.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb==0.3.21) (6.1.0)
Collecting duckdb>=0.7.1 (from chromadb==0.3.21)
  Using cached duckdb-1.5.6-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Collecting fastapi>=0.85.1 (from chromadb==0.3.21)
  Using cached fastapi-0.151.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.3.21) (0.54.0)
Requirement already satisfied: numpy>=1.21.6 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb==0.3.21) (2.5.4)
Collecting posthog>=2.4.0 (from chromadb==0.3.21)
  Downloading posthog-7.73.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: packaging in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from faiss-cpu>=1.8.0) (26.3)
Requirement already satisfied: certifi in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from clickhouse-connect>=0.5.7->chromadb==0.3.21) (2026.7.22)
Requirement already satisfied: urllib3>=1.26 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from clickhouse-connect>=0.5.7->chromadb==0.3.21) (2.8.0)
Requirement already satisfied: tzdata in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from clickhouse-connect>=0.5.7->chromadb==0.3.21) (2026.4)
Collecting backports.zstd>=1.3.0 (from clickhouse-connect>=0.5.7->chromadb==0.3.21)
  Using cached backports_zstd-1.8.0-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Collecting lz4 (from clickhouse-connect>=0.5.7->chromadb==0.3.21)
  Using cached lz4-4.4.5-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Collecting starlette>=0.46.0 (from fastapi>=0.85.1->chromadb==0.3.21)
  Using cached starlette-1.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting pydantic>=1.9 (from chromadb==0.3.21)
  Using cached pydantic-2.14.1-py3-none-any.whl.metadata (133 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from fastapi>=0.85.1->chromadb==0.3.21) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from fastapi>=0.85.1->chromadb==0.3.21) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from fastapi>=0.85.1->chromadb==0.3.21) (0.0.5)
Requirement already satisfied: opentelemetry-api>=1.44.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from fastapi>=0.85.1->chromadb==0.3.21) (1.45.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pandas>=1.3->chromadb==0.3.21) (2.9.0.post0)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb==0.3.21)
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting distro>=1.5.0 (from posthog>=2.4.0->chromadb==0.3.21)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic>=1.9->chromadb==0.3.21) (0.8.0)
Collecting pydantic-core==2.50.1 (from pydantic>=1.9->chromadb==0.3.21)
  Using cached pydantic_core-2.50.1-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from requests>=2.28->chromadb==0.3.21) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from requests>=2.28->chromadb==0.3.21) (3.19)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21) (5.20.2)
Requirement already satisfied: tokenizers>=0.19 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21) (0.23.3)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21) (1.33.0)
Requirement already satisfied: torch>=2.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21) (2.14.0)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21) (1.9.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21) (1.17.1)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers>=2.2.2->chromadb==0.3.21) (4.70.1)
Requirement already satisfied: click>=7.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn>=0.18.3->uvicorn[standard]>=0.18.3->chromadb==0.3.21) (8.5.0)
Requirement already satisfied: h11>=0.8 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn>=0.18.3->uvicorn[standard]>=0.18.3->chromadb==0.3.21) (0.16.0)
Requirement already satisfied: httptools>=0.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.3.21) (0.9.0)
Requirement already satisfied: python-dotenv>=0.13 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.3.21) (1.2.4)
Requirement already satisfied: pyyaml>=5.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.3.21) (6.0.3)
Requirement already satisfied: watchfiles>=0.20 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.3.21) (1.3.0)
Requirement already satisfied: websockets>=13.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.3.21) (17.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (4.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (0.28.1)
Requirement already satisfied: six>=1.5 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3->chromadb==0.3.21) (1.17.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (3.7.0)
Requirement already satisfied: anyio<5,>=4.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from starlette>=0.46.0->fastapi>=0.85.1->chromadb==0.3.21) (4.15.1)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers>=2.2.2->chromadb==0.3.21) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers>=2.2.2->chromadb==0.3.21) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers>=2.2.2->chromadb==0.3.21) (3.7)
Requirement already satisfied: jinja2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers>=2.2.2->chromadb==0.3.21) (3.1.6)
Requirement already satisfied: colorama in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from tqdm>=4.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (0.4.6)
Requirement already satisfied: regex>=2025.10.22 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (2026.9.29)
Requirement already satisfied: typer in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (0.8.0)
Requirement already satisfied: httpcore==1.* in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (1.0.9)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers>=2.2.2->chromadb==0.3.21) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from jinja2->torch>=2.2->sentence-transformers>=2.2.2->chromadb==0.3.21) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (15.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=2.2.2->chromadb==0.3.21) (0.1.2)
Using cached chromadb-0.3.21-py3-none-any.whl (46 kB)
Using cached clickhouse_connect-1.11.0-cp312-cp312-win_amd64.whl (458 kB)
Using cached duckdb-1.5.6-cp312-cp312-win_amd64.whl (13.2 MB)
Using cached fastapi-0.151.0-py3-none-any.whl (145 kB)
Downloading posthog-7.73.1-py3-none-any.whl (894 kB)
   ---------------------------------------- 0.0/894.5 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/894.5 kB ? eta -:--:--
   ---------------------------------------- 894.5/894.5 kB 4.1 MB/s eta 0:00:00
Using cached pydantic-2.14.1-py3-none-any.whl (488 kB)
Using cached pydantic_core-2.50.1-cp312-cp312-win_amd64.whl (2.2 MB)
Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Using cached backports_zstd-1.8.0-cp312-cp312-win_amd64.whl (330 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Using cached starlette-1.9.0-py3-none-any.whl (80 kB)
Using cached lz4-4.4.5-cp312-cp312-win_amd64.whl (99 kB)
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (pyproject.toml): started
  Building wheel for hnswlib (pyproject.toml): finished with status 'error'
Failed to build hnswlib
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Unable to find a compatible Visual Studio installation.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Failed to build installable wheels for some pyproject.toml based projects (hnswlib)

Collecting numpy<2
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: sentence-transformers in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (6.1.0)
Requirement already satisfied: transformers in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (5.20.2)
Requirement already satisfied: tokenizers>=0.19 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (0.23.3)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=2.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (2.14.0)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (1.9.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.10.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (4.70.1)
Requirement already satisfied: packaging>=20.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers) (2026.9.29)
Requirement already satisfied: typer in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: colorama in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: anyio in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.15.1)
Requirement already satisfied: certifi in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.4
    Uninstalling numpy-2.5.4:
      Successfully uninstalled numpy-2.5.4
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chromadb 1.5.9 requires pydantic>=2.0, but you have pydantic 1.10.26 which is incompatible.
contourpy 1.4.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
ml-dtypes 0.6.0 requires numpy>=2.0.0, but you have numpy 1.26.4 which is incompatible.
spacy 3.8.16 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.26 which is incompatible.
thinc 8.3.13 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.26 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip uninstall -y pydantic pydantic-core numpy pyarrow datasets
%pip install -U "numpy>=2" pyarrow datasets pydantic
%pip install -U faiss-cpu chromadb sentence-transformers transformers

Found existing installation: pydantic 1.10.26
Uninstalling pydantic-1.10.26:
  Successfully uninstalled pydantic-1.10.26
Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: pyarrow 26.0.0
Uninstalling pyarrow-26.0.0:
  Successfully uninstalled pyarrow-26.0.0
Found existing installation: datasets 5.1.0
Uninstalling datasets-5.1.0:
  Successfully uninstalled datasets-5.1.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping pydantic-core as it is not installed.

Collecting numpy>=2
  Using cached numpy-2.5.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting pyarrow
  Using cached pyarrow-26.0.0-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Collecting datasets
  Using cached datasets-5.1.0-py3-none-any.whl.metadata (24 kB)
Collecting pydantic
  Using cached pydantic-2.14.1-py3-none-any.whl.metadata (133 kB)
Requirement already satisfied: filelock in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (4.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (3.0.5)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (4.70.1)
Requirement already satisfied: xxhash in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.7.0,>=2023.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2026.7.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (1.33.0)
Requirement already satisfied: packaging in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic) (0.8.0)
Collecting pydantic-core==2.50.1 (from pydantic)
  Using cached pydantic_core-2.50.1-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.16.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.4 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic) (0.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (3.14.5)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (0.28.1)
Requirement already satisfied: colorama in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pandas->datasets) (2026.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.25.1)
Requirement already satisfied: anyio in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (4.15.1)
Requirement already satisfied: certifi in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Using cached numpy-2.5.4-cp312-cp312-win_amd64.whl (12.6 MB)
Using cached pyarrow-26.0.0-cp312-cp312-win_amd64.whl (28.6 MB)
Using cached datasets-5.1.0-py3-none-any.whl (604 kB)
Using cached pydantic-2.14.1-py3-none-any.whl (488 kB)
Using cached pydantic_core-2.50.1-cp312-cp312-win_amd64.whl (2.2 MB)
Installing collected packages: pydantic-core, pyarrow, numpy, pydantic, datasets
Successfully installed datasets-5.1.0 numpy-2.5.4 pyarrow-26.0.0 pydantic-2.14.1 pydantic-core-2.50.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: faiss-cpu in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (1.15.1)
Requirement already satisfied: chromadb in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (1.5.9)
Requirement already satisfied: sentence-transformers in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (6.1.0)
Requirement already satisfied: transformers in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (5.20.2)
Requirement already satisfied: numpy>=1.25 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from faiss-cpu) (2.5.4)
Requirement already satisfied: packaging in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from faiss-cpu) (26.3)
Requirement already satisfied: build>=1.0.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic>=2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (2.14.1)
Requirement already satisfied: pydantic-settings>=2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (2.16.0)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (1.5.1)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.54.0)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (4.16.0)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (1.31.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (1.45.1)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (0.23.3)
Requirement already satisfied: pypika>=0.48.9 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (4.70.1)
Requirement already satisfied: overrides>=7.3.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (1.84.0)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (0.27.2)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (37.0.1)
Requirement already satisfied: tenacity>=8.2.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (9.2.1)
Requirement already satisfied: pyyaml>=6.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (5.3.1)
Requirement already satisfied: orjson>=3.9.12 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (3.13.0)
Requirement already satisfied: httpx>=0.27.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (15.0.0)
Requirement already satisfied: jsonschema>=4.19.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from chromadb) (4.26.0)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=2.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (2.14.0)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (1.9.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: regex>=2025.10.22 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers) (2026.9.29)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: pyproject_hooks in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: colorama in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: anyio in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx>=0.27.0->chromadb) (4.15.1)
Requirement already satisfied: certifi in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx>=0.27.0->chromadb) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpx>=0.27.0->chromadb) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.7.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from jsonschema>=4.19.0->chromadb) (2026.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.34.2)
Requirement already satisfied: requests-oauthlib in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3<3.0.0,>=2.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)
Requirement already satisfied: durationpy>=0.11 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: aiohttp<4.0.0,>=3.14.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (3.14.5)
Requirement already satisfied: aiohttp-retry>=2.9.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.9.1)
Requirement already satisfied: flatbuffers in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (7.36.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-proto==1.45.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.66b1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic>=2.0->chromadb) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic>=2.0->chromadb) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic>=2.0->chromadb) (0.4.4)
Requirement already satisfied: python-dotenv>=1.2.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from pydantic-settings>=2.0->chromadb) (1.2.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from rich>=10.11.0->chromadb) (2.21.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from typer>=0.9.0->chromadb) (0.0.5)
Requirement already satisfied: httptools>=0.8.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.9.0)
Requirement already satisfied: watchfiles>=0.20 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.3.0)
Requirement already satisfied: websockets>=13.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (17.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from aiohttp<4.0.0,>=3.14.3->kubernetes>=28.1.0->chromadb) (1.25.1)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: six>=1.5 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from python-dateutil>=2.8.2->kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from requests->kubernetes>=28.1.0->chromadb) (3.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\avigd\desktop\genai\.venv2\lib\site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (4.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# %pip install -U tf-keras

In [4]:
import os
import json
from pathlib import Path
import numpy as np
import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer, InputExample
import chromadb
from chromadb.config import Settings
import os
os.environ['USE_TF'] = '0'
os.environ['TRANSFORMERS_NO_TF'] = '1'
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from IPython.display import display

os.makedirs('cache', exist_ok=True)

c:\Users\avigd\Desktop\GENAI\.venv2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 🌟 Exercise 1 · Data loading and preparation

In [5]:
data_path = 'labelled_newscatcher_dataset.csv'
pdf = pd.read_csv(data_path, sep=';')
if 'id' not in pdf.columns:
    pdf['id'] = range(len(pdf))
display(pdf.head())
pdf_subset = pdf.head(1000)
pdf_subset[['id', 'title']].head()

,topic,link,domain,published_date,title,lang,id
0,SCIENCE,https://www.eurekalert.org/pub_releases/2020-0...,eurekalert.org,2020-08-06 13:59:45,A closer look at water-splitting's solar fuel ...,en,0
1,SCIENCE,https://www.pulse.ng/news/world/an-irresistibl...,pulse.ng,2020-08-12 15:14:19,"An irresistible scent makes locusts swarm, stu...",en,1
2,SCIENCE,https://www.express.co.uk/news/science/1322607...,express.co.uk,2020-08-13 21:01:00,Artificial intelligence warning: AI will know ...,en,2
3,SCIENCE,https://www.ndtv.com/world-news/glaciers-could...,ndtv.com,2020-08-03 22:18:26,Glaciers Could Have Sculpted Mars Valleys: Study,en,3
4,SCIENCE,https://www.thesun.ie/tech/5742187/perseid-met...,thesun.ie,2020-08-12 19:54:36,Perseid meteor shower 2020: What time and how ...,en,4

   id                                              title
0   0  A closer look at water-splitting's solar fuel ...
1   1  An irresistible scent makes locusts swarm, stu...
2   2  Artificial intelligence warning: AI will know ...
3   3   Glaciers Could Have Sculpted Mars Valleys: Study
4   4  Perseid meteor shower 2020: What time and how ...

## 🌟 Exercise 2 · Vectorization with Sentence Transformers

In [6]:
def example_create_fn(idx: int, text: str) -> InputExample:
    return InputExample(guid=str(idx), texts=[text], label=0.0)

faiss_train_examples = [example_create_fn(idx, title) for idx, title in enumerate(pdf_subset['title'])]
faiss_train_examples[:2]

[<sentence_transformers.sentence_transformer.readers.input_example.InputExample at 0x2ba11ff3500>,
 <sentence_transformers.sentence_transformer.readers.input_example.InputExample at 0x2ba10b479e0>]

In [7]:
model = SentenceTransformer('all-MiniLM-L6-v2')
titles_list = pdf_subset['title'].tolist()
faiss_title_embedding = model.encode(titles_list, convert_to_numpy=True, show_progress_bar=True)
len(faiss_title_embedding), len(faiss_title_embedding[0])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1872.62it/s]
Batches: 100%|██████████| 32/32 [00:02<00:00, 10.80it/s]

(1000, 384)

## 🌟 Exercise 3 · FAISS indexing and search

In [8]:
pdf_to_index = pdf_subset
id_index = pdf_to_index['id'].to_numpy().astype(np.int64)
content_encoded_normalized = faiss_title_embedding.astype('float32')
faiss.normalize_L2(content_encoded_normalized)
index_content = faiss.IndexIDMap(faiss.IndexFlatIP(content_encoded_normalized.shape[1]))
index_content.add_with_ids(content_encoded_normalized, id_index)
index_content.ntotal

1000

In [9]:
def search_content(query: str, pdf_to_index: pd.DataFrame, k: int = 3):
    query_vector = model.encode([query], convert_to_numpy=True)
    faiss.normalize_L2(query_vector)
    sims, ids = index_content.search(query_vector, k)
    results = pdf_to_index[pdf_to_index['id'].isin(ids[0])].copy()
    results['similarities'] = sims[0]
    return results

display(search_content('animal', pdf_to_index, k=5))

,topic,link,domain,published_date,title,lang,id,similarities
99,TECHNOLOGY,https://www.gematsu.com/2020/08/ghostwire-toky...,gematsu.com,2020-08-07 16:43:13,Ghostwire: Tokyo confirms dog petting,en,99,0.391902
176,TECHNOLOGY,https://www.pushsquare.com/news/2020/08/random...,pushsquare.com,2020-08-03 16:30:00,Random: You Can Pick Up and Pet Cats in Assass...,en,176,0.376784
762,SCIENCE,https://af.reuters.com/article/worldNews/idAFK...,af.reuters.com,2020-08-13 16:51:00,'Secret' life of sharks: Study reveals their s...,en,762,0.344059
928,SCIENCE,https://www.thecut.com/2020/08/scientists-say-...,thecut.com,2020-08-04 12:52:00,Just Let This Lizard Be a Dinosaur,en,928,0.317387
975,HEALTH,https://www.news-medical.net/news/20200813/Res...,news-medical.net,2020-08-13 05:18:00,Researchers explore social behavior of animals...,en,975,0.295497

## 🌟 Exercise 4 · ChromaDB collection and querying

In [10]:
chroma_client = chromadb.Client(Settings(anonymized_telemetry=False))
collection_name = 'my_news'
if any(c.name == collection_name for c in chroma_client.list_collections()):
    chroma_client.delete_collection(name=collection_name)
collection = chroma_client.create_collection(name=collection_name)
collection.add(
    ids=[str(i) for i in pdf_subset['id']],
    documents=pdf_subset['title'].tolist(),
    metadatas=[{'topic': t} for t in pdf_subset['topic']]
)
results = collection.query(query_texts=['animal'], n_results=5)
print(json.dumps(results, indent=2))

{
  "ids": [
    [
      "176",
      "975",
      "99",
      "928",
      "762"
    ]
  ],
  "embeddings": null,
  "documents": [
    [
      "Random: You Can Pick Up and Pet Cats in Assassin's Creed Valhalla",
      "Researchers explore social behavior of animals toward emerging infectious diseases",
      "Ghostwire: Tokyo confirms dog petting",
      "Just Let This Lizard Be a Dinosaur",
      "'Secret' life of sharks: Study reveals their surprising social networks"
    ]
  ],
  "uris": null,
  "included": [
    "metadatas",
    "documents",
    "distances"
  ],
  "data": null,
  "metadatas": [
    [
      {
        "topic": "TECHNOLOGY"
      },
      {
        "topic": "HEALTH"
      },
      {
        "topic": "TECHNOLOGY"
      },
      {
        "topic": "SCIENCE"
      },
      {
        "topic": "SCIENCE"
      }
    ]
  ],
  "distances": [
    [
      1.216196060180664,
      1.2464325428009033,
      1.3118830919265747,
      1.3652255535125732,
      1.409005880355835
    ]
  ]
}

## 🌟 Exercise 5 · Question answering with a Hugging Face model

In [11]:
# %pip install -U "transformers<5"

In [12]:
# model_id = 'google/flan-t5-small'  # lightweight, better than tiny GPT-2 for QA
# # To-Do: create the text2text-generation pipeline
# pipe = pipeline('text2text-generation', model=model_id)

# question = "What's the latest news on space development?"
# context_docs = results['documents'][0][:3]
# context = ' '.join(context_docs)
# prompt = f"Answer the question using only the context.\nContext: {context}\nQuestion: {question}\nAnswer:\n"
# response = pipe(prompt)[0]['generated_text']
# print(response)

from transformers import AutoModelForSeq2SeqLM

model_id = 'google/flan-t5-small'
tokenizer = AutoTokenizer.from_pretrained(model_id)
seq2seq_model = AutoModelForSeq2SeqLM.from_pretrained(model_id)

question = "What's the latest news on space development?"
context_docs = results['documents'][0][:3]
context = ' '.join(context_docs)
prompt = f"Answer the question using only the context.\nContext: {context}\nQuestion: {question}\nAnswer:\n"

inputs = tokenizer(prompt, return_tensors='pt', truncation=True)
output_ids = seq2seq_model.generate(**inputs, max_new_tokens=50)
response = tokenizer.decode(output_ids[0], skip_special_tokens=True)
print(response)

Loading weights: 100%|██████████| 190/190 [00:00<00:00, 1688.90it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

Ghostwire: Tokyo confirms dog petting